storage: /verdaccio/storage

web:
  enable: ${WEB_ENABLE}
  title: ${WEB_TITLE}

auth:
  activedirectory:
    url: ldap://${DOMAIN}
    baseDN: ${BASE_DN}
    domainSuffix: ${DOMAIN}

uplinks:
  npmjs:
    url: ${PROXY}

packages:
  '@*/*':
    access: ${SCOPED}
    publish: ${SCOPED}
    proxy: npmjs

  '**':
    access: ${BASIC}
    publish: ${BASIC}
    proxy: npmjs

logs:
  - type: stdout
    format: pretty
    level: trace

listen:
  - 0.0.0.0:${PORT}
